# Netflix Eureka Service Discovery Configurations
server.port=8761

# Disable self-registration as a client
eureka.client.register-with-eureka=false

# Disable registry cache fetching
eureka.client.fetch-registry=false

# Service dashboard logging level
logging.level.org.springframework.cloud=INFO
